### PR TITLE
MNT: bids2scidata: Use .iloc instead of deprecated .ix

### PR DESCRIPTION
**Pull request by kyleam**
This popped up in the "DeprecationWarning -> error" run from datalad/datalad#3618: https://travis-ci.org/datalad/datalad/jobs/576041485#L1241

### CODE REVIEW

**Comment by yarikoptic** [comment]
```
======================================================================
ERROR: datalad_neuroimaging.tests.test_bids2scidata.test_real_ds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad-neuroimaging/build/lib/datalad_neuroimaging/tests/test_bids2scidata.py", line 163, in test_real_ds
    ds = install(source=get_bids_dataset().path, path=path, reckless=True)
  File "/home/travis/build/datalad/datalad-neuroimaging/build/lib/datalad_neuroimaging/tests/utils.py", line 107, in get_bids_dataset
    message="DICOM conversion of {} scans".format(label))
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/distribution/dataset.py", line 526, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/utils.py", line 480, in return_func
    results = list(results)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/utils.py", line 429, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/utils.py", line 522, in _process_results
    for res in results:
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/run.py", line 218, in __call__
    sidecar=sidecar):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/run.py", line 623, in run_command
    raise exc
CommandError: CommandError: command 'heudiconv -f reproin -s 02 -c dcm2niix -o /tmp/datalad_temp_vIzfJ_/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids/.git/stupid/structural -b -a /tmp/datalad_temp_vIzfJ_/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids -l '' --minmeta --files /tmp/datalad_temp_vIzfJ_/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids/sourcedata/sub-02/ses-structural/dicoms' failed with exitcode 1
Failed to run u"heudiconv -f reproin -s 02 -c dcm2niix -o /tmp/datalad_temp_vIzfJ_/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids/.git/stupid/structural -b -a /tmp/datalad_temp_vIzfJ_/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids -l '' --minmeta --files /tmp/datalad_temp_vIzfJ_/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids/sourcedata/sub-02/ses-structural/dicoms" under '/tmp/datalad_temp_vIzfJ_/.cache/datalad/datalad_neuroimaging_srcrepo/datalad_neuroimaging/tests/data/bids'. Exit code=1.
```
and previous PR build (11 days ago though) didn't have this failure

**Comment by yarikoptic** [comment]
restarted that PR #73 [travis build](https://travis-ci.org/datalad/datalad-neuroimaging/builds/571411987?utm_source=github_status) to see what is failing there now

**Comment by kyleam** [comment]
I think this should resolve the failure that @mih just [noted][0] in datalad core, so I'll rebase this and see how the tests here look.

[0]: https://github.com/datalad/datalad/pull/4108#issuecomment-580318920

**Comment by kyleam** [comment]
The [test failures][0] are unrelated.  They're due to nipype_workshop_dataset.sh passing `-S` to `datalad save`, which isn't supported on 0.12.

[0]: https://travis-ci.org/datalad/datalad-neuroimaging/builds/643935498

**Comment by mih** [comment]
LGTM

**Pull request merged**
