### PR TITLE
Improved BIDS config procedure

### LINKED ISSUE #35: Move BIDS procedure here
https://github.com/psychoinformatics-de/datalad-hirni/issues/43

Once that is done we could investigate how much of that is an overfit and could be RF'ed into a procedure that ships with this package.

### PR DESCRIPTION
**Pull request by mih**
Fixes #35

### CODE REVIEW

**Comment by yarikoptic** [comment]
I don't see the point in retaining `_dataset` suffix, eg do you expect pure `bids` procedure which somehow will be different?

**Comment by mih** [comment]
I would prefer not to have a just `bids` procedure. It is a growing ecosystem that may want us to support other flavours of BIDS in dedicated procedures. I still regret the decision to have a `create-sibling` and a week later `create-sibling-github`.

That being said, a `_dataset` suffix is not helpful in this regard. It might make sense to encode a version,e.g. `bids_v1` or a flavour `bids_raw` (vs. a later `bids_derivative`). Not sure which one I'd prefer, but not just `bids`.

**Comment by yarikoptic** [comment]
We will indeed probably have some kind of `bids_derivative` at some point unless I fully succeed in persuading that actually any bids dataset is actually a derivative dataset (we kinda 80% there), so e.g. we could list [PipelineDescription](https://bids-specification.readthedocs.io/en/derivatives/05-derivatives/01-introduction.html#derived-dataset-and-pipeline-description) within `dataset_description.json` for HeuDiConv/ReproIn conversion or HIRNI for "raw" BIDS datasets.  So indeed there would be more "specific" procedures but may be it should still be the same procedure?

Re `create-sibling` vs `create-sibling-github`,  let's just say that it is not a fault of `create-sibling` and it just attests to desire to have a single common command (instead of collection with various suffixes) as we have already `subdatasets`, `siblings`, and may be in the future `containers` (instead of `containers-list`) if we figure out how to "parametrize" additional actions/parametrizations scalably/flexibly.  E.g. here `bids_derivative` is probably just a flavor of `bids`, so we could may be better encode/interface parameters of the procedures? i.e. I want `bids` which supports `derivatives` specification and may be some other specifics which might be orthogonal to being bids raw or derivative (e.g. multisession vs single session) and thus ideally be in a single command and not elevating one aspect (raw-vs-derivative, or single-vs-multisession) into procedure name.
In the case of [-c](https://github.com/datalad/datalad/pull/3353) we probably then should follow (for consistency) what you have already for --proc-pre/post: `--proc-pre <PROCEDURE NAME> [ARGS ...]`: `-c bids derivative` or `-c bids flavor=derivative`, although I dislike those open ended options and preferred some encoding within the name (`-c bids[derivative]` or `-c bids[flavor=derivative]`).

**Comment by mih** [comment]
Ok, rename is done.

**Pull request merged**
