### PR TITLE
WIP: Add travis matrix runs for devel version of datalad and heudiconv

### PR DESCRIPTION
**Pull request by yarikoptic**
Apparently something is missing in heudiconv setup which seems to cause issues... will check later

### CODE REVIEW

**Comment by yarikoptic** [comment]
1. Changes within neuroimaging can break compatibility with released or development certain of datalad. Without development run here you wouldn't know until pr is merged. It is similar to us in datalad testing against development version of git annex and git now
2. dcmstack afaik was fixed up and no custom branch installation should be needed, heudiconv should depend on it... If something doesn't work, most likely needs fix or release in heudiconv

**Comment by bpoldrack** [comment]
> Without development run here you wouldn't know until pr is merged

Well, true. Just wondering, what to do here, if released datalad passes and master doesn't. What's the strategy towards merge here? Do we require neuroimaging PRs to account for unreleased changes in datalad? Or should such failure just raise attention (so -> allow_failure)?

**Comment by yarikoptic** [comment]
> > Without development run here you wouldn't know until pr is merged
> 
> Well, true. Just wondering, what to do here, if released datalad passes and master doesn't. What's the strategy towards merge here? Do we require neuroimaging PRs to account for unreleased changes in datalad? Or should such failure just raise attention (so -> allow_failure)?

Great question!  Given that DataLad's master strives to be fully functional, and here we do not claim some extra powers (like Windows support) I would say that we should strive to keep this one "compatible" with both released and master version of datalad.  If PR testing fails:

- because introduced here changes are not compatible with master or released -- needs fix here
- because datalad master has a bug -- nothing to do here, just file/fix in datalad 

Whenever master of DataLad becomes "experimental" again (currently with all the `rc` I would call it "unstable"), we might reconsider ;-)

**Comment by mih** [comment]
We have the extension test machinery now. Is this still needed as a special case?

**Comment by yarikoptic** [comment]
yeah -- datalad-extensions addressed the issue of testing against the mothership datalad.  `heudiconv` is IMHO a bit too heavy of a "testing helper" and eventually should probably just be replaced with use of some specific/precrafted datasets, and not bother using it here in a fixture. overall -- I am ok to let this PR RiP

**Pull request closed without merging**
