### PR TITLE
Add a minc metadata extractor

### PR DESCRIPTION
**Pull request by driusan**
This adds a minc metadata extractor which extracts metadata
from minc files.

It depends on minc2_simple from https://github.com/vfonov/minc2-simple
to be installed.

### CODE REVIEW

**Comment by mih** [comment]
Thanks for the PR @driusan!

Question is how we can get this running with travis?

#### Dependency on libminc2

It seems Ubuntu trusty (travis default) has `libminc2-3`. Would that be enough? Xenial is also an option and comes with `libminc2-4.0.0`. If both don't work, we would have to look into backports. Latest Debian is `libminc2-5.2.0`.

#### Dependency on minc2_simple

This Python package is not in PyPi and sources are just a part of the https://github.com/vfonov/minc2-simple repository (under `python/`). This effectively prevents simple deployment via `pip`. While this can be worked around in all kinds of ways, any hack will come back as a user-deployment issue. Ideally there would be a PyPi release.

#### General notes

I am almost done with the new extractor interface that is coming here: https://github.com/datalad/datalad-revolution/pull/84

I can confirm that this code is easy to port.

Please have a look at https://github.com/datalad/datalad/pull/3329 This PR changes a pattern that is also used here: "Try to open all the files, and see if that works". This can lead to substantial slow-down and it might be useful to add a file name based rejection into the main for-loop across files.

**Comment by driusan** [comment]
I'm far from an expert on Python package management, perhaps @vfonov might have some ideas on how feasible it would be to get minc2-simple pip installable or knows how stable libminc2 is across versions.

**Comment by driusan** [comment]
I'm skimming https://github.com/datalad/datalad/pull/3329/files and I don't see why that would be faster than this.

Why is 

```python
if fname_match_regex.match(f, re.IGNORECASE) is None:
    continue
```

(theoretically) faster than

```python
if f.endswith(".mnc"):
    files.append(f)
```

? In either case, it should be only checking files that have a given file extension, as far as I can tell.

**Comment by vfonov** [comment]
in short, it is complicated. 
The simplest way to install inside travis would be  to use conda, i.e "conda install -c vfonov minc-toolkit-v2 minc2-simple " , this of course will install much more then just libminc and a python module.

**Comment by mih** [comment]
@driusan I was too fast -- missed that these are two functions. I cannot possibly be faster. All good.

**Comment by vfonov** [comment]
Also, side note - minc2-simple will extract metadata from MINC1, but will do it quite ineffectively, by converting the whole file to minc2 format first (creating a file in /tmp). So, beware when indexing huge archives.

**Comment by driusan** [comment]
@mih @yarikoptic do things fail loudly or cause anything to break if a extractor has a dependency that's unfulfilled, but the extractor hasn't been explicitly enabled in a dataset? I'm wondering if using conda or compiling from source would work under Travis, with a note for end users telling them they need to manually install minc2-simple if they want to enable the minc extractor.

**Comment by driusan** [comment]
renamed from minc2 to minc and updated the commit description to say it does both minc and minc2..

**Comment by yarikoptic** [comment]
If it comes to conda -- we could adjust CI to have a run in conda, and it would get tested.  If it comes to NeuroDebian -- everybody wins! ;)

**Comment by mih** [comment]
As with https://github.com/datalad/datalad-neuroimaging/pull/3, I am closing this now. After a lot of work, https://github.com/datalad/datalad-metalad  is slowly getting in shape to provide the framework for pick ing this effort up again. @driusan thanks for your work -- it will not have been in vain.

**Pull request closed without merging**
